# Mathematical Ops

In [2]:
import numpy as np

In [3]:
arr_01 = np.arange(1,10).reshape(3,3)
arr_02 = np.arange(1,10).reshape(3,3)
print(arr_01)
print(arr_02)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
# Addition
arr_01+arr_02

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [6]:
arr_add = np.add(arr_01,arr_02)
print(arr_add)


[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [7]:
# Subtraction
arr_01-arr_02

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [9]:
arr_sub = np.subtract(arr_01,arr_02)
print(arr_sub)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [10]:
# Multiply
arr_01*arr_02

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [11]:
arr_mul = np.multiply(arr_01,arr_02)
print(arr_mul)

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [12]:
# Division
arr_01/arr_02

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [13]:
arr_div = np.divide(arr_01,arr_02)
print(arr_div)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [14]:
# Matrix Multiplication
arr_01@arr_02

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [15]:
arr_mat_mul = arr_01.dot(arr_02)
print(arr_mat_mul)

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


# Max,Min and Numerical OPS

In [16]:
# max element from array
arr_test = np.arange(1,10).reshape(3,3)
arr_test.max()


9

In [17]:
# max index 
arr_test.argmax()

8

In [23]:
# max from col or row
# axis=0 -> col
# axis=1 -> row
arr_test = np.arange(1,10).reshape(3,3)
arr_test
print(arr_test)
print(arr_test.max(axis=0))
print(arr_test.max(axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[7 8 9]
[3 6 9]


In [24]:
# min from col or row
# axis=0 -> col
# axis=1 -> row
arr_test = np.arange(1,10).reshape(3,3)
arr_test
print(arr_test)
print(arr_test.min(axis=0))
print(arr_test.min(axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]
[1 4 7]
