In [1]:
import numpy as np

In [2]:
arr_01 = np.arange(1,101).reshape(10,10)
print(arr_01)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


In [3]:
# Get Element = [row,column]

In [4]:
arr_01[0,3]

4

In [5]:
arr_01[0:2 , 0]    # arr[row , column]
                   # [: , :] -> denotes entire row and col

array([ 1, 11])

In [7]:
arr_01[: , 0:4]

array([[ 1,  2,  3,  4],
       [11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34],
       [41, 42, 43, 44],
       [51, 52, 53, 54],
       [61, 62, 63, 64],
       [71, 72, 73, 74],
       [81, 82, 83, 84],
       [91, 92, 93, 94]])

In [8]:
arr_01[0,5]

6

In [9]:
arr_01[0,5].ndim

0

In [10]:
arr_01[: , 0:4].ndim

2