In [1]:
import numpy as np

In [2]:
arr_1 = np.array([1,2,3,4])
print(arr_1)

[1 2 3 4]


In [4]:
arr_2 = np.array([[1,2,3,4],[5,6,7,8]])
print(arr_2)

[[1 2 3 4]
 [5 6 7 8]]


In [5]:
type(arr_2)

numpy.ndarray

In [6]:
arr_2.shape #row vs col

(2, 4)

In [7]:
arr_2.size #elem_no.

8

In [8]:
arr_2.ndim #dimension

2