In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
import matplotlib.pyplot as plt

In [3]:
digits = load_digits()
dir(digits)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [4]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(digits.data,digits.target,test_size=0.2)

In [5]:
# logistic regression
log_reg = LogisticRegression()
log_reg.fit(X_train,Y_train)
log_reg.score(X_test,Y_test)

C:\Users\RAJARSHI RAY\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9666666666666667

In [7]:
# SVM
svm_reg = SVC(gamma='auto')
svm_reg.fit(X_train,Y_train)
svm_reg.score(X_test,Y_test)

0.49166666666666664

In [8]:
for_reg = RandomForestClassifier(n_estimators=50)
for_reg.fit(X_train,Y_train)
for_reg.score(X_test,Y_test)

0.9861111111111112

In [9]:
# K Fold Cross Validation
from sklearn.model_selection import KFold
kfold = KFold(n_splits=5)    # n_splits -> no. of the folds of data
kfold

KFold(n_splits=5, random_state=None, shuffle=False)

In [11]:
for train_index,test_index in kfold.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)
    
    #[training data] [test data]
    # test data = 20%


[2 3 4 5 6 7 8] [0 1]
[0 1 4 5 6 7 8] [2 3]
[0 1 2 3 6 7 8] [4 5]
[0 1 2 3 4 5 8] [6 7]
[0 1 2 3 4 5 6 7] [8]


In [16]:
# KFold
def reg_score(model_reg,X_train,X_test,Y_train,Y_test):
    model_reg.fit(X_train,Y_train)
    return model_reg.score(X_test,Y_test)

In [17]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)
log_score = []
svm_score = []
rnf_score = []

for train_index,test_index in folds.split(digits.data,digits.target):
    X_train,X_test,Y_train,Y_test = digits.data[train_index],digits.data[test_index],digits.target[train_index],digits.target[test_index]
    log_score.append(reg_score(LogisticRegression(),X_train,X_test,Y_train,Y_test))
    svm_score.append(reg_score(SVC(gamma="auto"),X_train,X_test,Y_train,Y_test))
    rnf_score.append(reg_score(RandomForestClassifier(n_estimators=50),X_train,X_test,Y_train,Y_test))
    

C:\Users\RAJARSHI RAY\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\RAJARSHI RAY\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://sciki

In [19]:
log_score

[0.9215358931552587, 0.9415692821368948, 0.9165275459098498]

In [20]:
svm_score

[0.3806343906510851, 0.41068447412353926, 0.5125208681135225]

In [21]:
rnf_score

[0.9315525876460768, 0.9549248747913188, 0.9265442404006677]

In [22]:
# cross val score
from sklearn.model_selection import cross_val_score

In [23]:
cross_val_score(LogisticRegression(),digits.data,digits.target,cv=3)


C:\Users\RAJARSHI RAY\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\RAJARSHI RAY\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://sciki

array([0.92153589, 0.94156928, 0.91652755])